[2024-11-10T12:04:32.824+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T11:44:29.056539+00:00/task_id=calculate_missing_average_temperature permission to 509
[2024-11-10T12:04:32.824+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T11:44:29.056539+00:00/task_id=calculate_missing_average_temperature permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T11:44:29.056539+00:00/task_id=calculate_missing_average_temperature'
[2024-11-10T12:04:32.852+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T11:44:29.056539+00:00/task_id=calculate_missing_average_temperature permission to 509
[2024-11-10T12:04:32.852+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T11:44:29.056539+00:00/task_id=calculate_missing_average_temperature permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T11:44:29.056539+00:00/task_id=calculate_missing_average_temperature'
[2024-11-10T12:04:32.897+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: noaa_etl_pipeline.calculate_missing_average_temperature manual__2024-11-10T11:44:29.056539+00:00 [queued]>
[2024-11-10T12:04:32.904+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: noaa_etl_pipeline.calculate_missing_average_temperature manual__2024-11-10T11:44:29.056539+00:00 [queued]>
[2024-11-10T12:04:32.904+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-10T12:04:32.917+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): calculate_missing_average_temperature> on 2024-11-10 11:44:29.056539+00:00
[2024-11-10T12:04:32.927+0000] {standard_task_runner.py:57} INFO - Started process 103555 to run task
[2024-11-10T12:04:32.929+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'noaa_etl_pipeline', 'calculate_missing_average_temperature', 'manual__2024-11-10T11:44:29.056539+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py', '--cfg-path', '/tmp/tmpe9pzd2dm']
[2024-11-10T12:04:32.931+0000] {standard_task_runner.py:85} INFO - Job 132: Subtask calculate_missing_average_temperature
[2024-11-10T12:04:32.970+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T11:44:29.056539+00:00/task_id=calculate_missing_average_temperature permission to 509
[2024-11-10T12:04:32.971+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T11:44:29.056539+00:00/task_id=calculate_missing_average_temperature permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T11:44:29.056539+00:00/task_id=calculate_missing_average_temperature'
[2024-11-10T12:04:32.972+0000] {task_command.py:415} INFO - Running <TaskInstance: noaa_etl_pipeline.calculate_missing_average_temperature manual__2024-11-10T11:44:29.056539+00:00 [running]> on host 16801ac1f6e4
[2024-11-10T12:04:33.049+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='noaa_etl_pipeline' AIRFLOW_CTX_TASK_ID='calculate_missing_average_temperature' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T11:44:29.056539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T11:44:29.056539+00:00'
[2024-11-10T12:08:41.150+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/transformation/noaa_api_transformation.py:139 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-11-10T12:08:41.154+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/transformation/noaa_api_transformation.py:140 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-11-10T12:08:41.156+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/transformation/noaa_api_transformation.py:141 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-11-10T12:08:41.159+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/transformation/noaa_api_transformation.py:142 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-11-10T12:08:41.161+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/transformation/noaa_api_transformation.py:143 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-11-10T12:09:13.887+0000] {local_task_job_runner.py:228} INFO - Task exited with return code -9
[2024-11-10T12:09:13.954+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
