[2024-11-10T05:55:05.208+0000] {processor.py:157} INFO - Started process (PID=57686) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:55:05.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:55:05.210+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:55:05.209+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:55:05.227+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:55:05.224+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:55:05.237+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:55:05.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.049 seconds
[2024-11-10T05:55:35.517+0000] {processor.py:157} INFO - Started process (PID=57753) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:55:35.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:55:35.518+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:55:35.518+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:55:35.529+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:55:35.527+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:55:35.530+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:55:35.556+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.041 seconds
[2024-11-10T05:56:05.848+0000] {processor.py:157} INFO - Started process (PID=57820) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:56:05.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:56:05.849+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:56:05.849+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:56:05.860+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:56:05.858+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:56:05.862+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:56:05.886+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.041 seconds
[2024-11-10T05:56:10.899+0000] {processor.py:157} INFO - Started process (PID=57825) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:56:10.899+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:56:10.900+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:56:10.900+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:56:10.921+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:56:10.918+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:56:10.922+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:56:10.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.043 seconds
[2024-11-10T05:56:41.396+0000] {processor.py:157} INFO - Started process (PID=57909) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:56:41.397+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:56:41.398+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:56:41.398+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:56:41.409+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:56:41.407+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:56:41.410+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:56:41.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T05:57:11.736+0000] {processor.py:157} INFO - Started process (PID=57976) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:57:11.736+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:57:11.737+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:57:11.737+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:57:11.750+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:57:11.747+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:57:11.751+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:57:11.776+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.043 seconds
[2024-11-10T05:57:42.046+0000] {processor.py:157} INFO - Started process (PID=58060) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:57:42.046+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:57:42.047+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:57:42.047+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:57:42.061+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:57:42.058+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:57:42.062+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:57:42.079+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.036 seconds
[2024-11-10T05:58:12.289+0000] {processor.py:157} INFO - Started process (PID=58127) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:58:12.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:58:12.291+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:58:12.290+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:58:12.302+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:58:12.300+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:58:12.303+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:58:12.321+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T05:58:42.525+0000] {processor.py:157} INFO - Started process (PID=58194) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:58:42.526+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:58:42.527+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:58:42.527+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:58:42.540+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:58:42.537+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:58:42.541+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:58:42.558+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.036 seconds
[2024-11-10T05:59:12.699+0000] {processor.py:157} INFO - Started process (PID=58261) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:59:12.700+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:59:12.700+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:59:12.700+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:59:12.713+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:59:12.710+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:59:12.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:59:12.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.036 seconds
[2024-11-10T05:59:43.039+0000] {processor.py:157} INFO - Started process (PID=58314) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:59:43.039+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T05:59:43.040+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:59:43.040+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:59:43.052+0000] {logging_mixin.py:151} INFO - [2024-11-10T05:59:43.049+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T05:59:43.053+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T05:59:43.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:00:13.215+0000] {processor.py:157} INFO - Started process (PID=58378) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:00:13.215+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:00:13.216+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:00:13.216+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:00:13.229+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:00:13.226+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:00:13.230+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:00:13.247+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:00:43.583+0000] {processor.py:157} INFO - Started process (PID=58445) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:00:43.584+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:00:43.585+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:00:43.585+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:00:43.596+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:00:43.594+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:00:43.597+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:00:43.613+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:01:13.800+0000] {processor.py:157} INFO - Started process (PID=58512) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:01:13.801+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:01:13.802+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:01:13.801+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:01:13.813+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:01:13.810+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:01:13.814+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:01:13.830+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:01:44.024+0000] {processor.py:157} INFO - Started process (PID=58579) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:01:44.025+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:01:44.026+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:01:44.025+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:01:44.037+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:01:44.035+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:01:44.038+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:01:44.057+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.035 seconds
[2024-11-10T06:02:14.240+0000] {processor.py:157} INFO - Started process (PID=58646) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:02:14.241+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:02:14.242+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:02:14.241+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:02:14.253+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:02:14.251+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:02:14.254+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:02:14.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:02:44.424+0000] {processor.py:157} INFO - Started process (PID=58707) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:02:44.424+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:02:44.425+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:02:44.425+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:02:44.440+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:02:44.438+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:02:44.441+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:02:44.458+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.037 seconds
[2024-11-10T06:03:14.746+0000] {processor.py:157} INFO - Started process (PID=58774) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:03:14.747+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:03:14.747+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:03:14.747+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:03:14.759+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:03:14.756+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:03:14.759+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:03:14.777+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:03:45.047+0000] {processor.py:157} INFO - Started process (PID=58841) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:03:45.048+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:03:45.049+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:03:45.049+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:03:45.062+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:03:45.060+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:03:45.063+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:03:45.080+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.035 seconds
[2024-11-10T06:04:15.305+0000] {processor.py:157} INFO - Started process (PID=58908) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:04:15.306+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:04:15.307+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:04:15.307+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:04:15.325+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:04:15.321+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:04:15.326+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:04:15.344+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.043 seconds
[2024-11-10T06:04:45.574+0000] {processor.py:157} INFO - Started process (PID=58975) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:04:45.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:04:45.576+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:04:45.576+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:04:45.588+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:04:45.585+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:04:45.589+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:04:45.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:05:15.894+0000] {processor.py:157} INFO - Started process (PID=59042) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:05:15.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:05:15.896+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:05:15.896+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:05:15.908+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:05:15.905+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:05:15.909+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:05:15.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.041 seconds
[2024-11-10T06:05:46.247+0000] {processor.py:157} INFO - Started process (PID=59109) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:05:46.248+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:05:46.249+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:05:46.249+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:05:46.262+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:05:46.259+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:05:46.263+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:05:46.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.035 seconds
[2024-11-10T06:06:16.506+0000] {processor.py:157} INFO - Started process (PID=59137) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:06:16.507+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:06:16.508+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:06:16.507+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:06:16.521+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:06:16.518+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:06:16.522+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:06:16.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.036 seconds
[2024-11-10T06:06:46.889+0000] {processor.py:157} INFO - Started process (PID=59204) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:06:46.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:06:46.890+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:06:46.890+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:06:46.901+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:06:46.899+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:06:46.902+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:06:46.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.040 seconds
[2024-11-10T06:07:17.117+0000] {processor.py:157} INFO - Started process (PID=59271) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:07:17.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:07:17.119+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:07:17.118+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:07:17.131+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:07:17.128+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:07:17.131+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:07:17.149+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:07:47.355+0000] {processor.py:157} INFO - Started process (PID=59338) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:07:47.356+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:07:47.357+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:07:47.357+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:07:47.369+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:07:47.366+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:07:47.370+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:07:47.387+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:08:17.537+0000] {processor.py:157} INFO - Started process (PID=59405) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:08:17.538+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:08:17.539+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:08:17.539+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:08:17.550+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:08:17.548+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:08:17.551+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:08:17.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.041 seconds
[2024-11-10T06:08:47.766+0000] {processor.py:157} INFO - Started process (PID=59472) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:08:47.767+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:08:47.767+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:08:47.767+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:08:47.782+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:08:47.780+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:08:47.784+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:08:47.801+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.037 seconds
[2024-11-10T06:09:17.997+0000] {processor.py:157} INFO - Started process (PID=59539) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:09:17.998+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:09:17.999+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:09:17.999+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:09:18.011+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:09:18.009+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:09:18.013+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:09:18.030+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.036 seconds
[2024-11-10T06:09:48.201+0000] {processor.py:157} INFO - Started process (PID=59606) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:09:48.202+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:09:48.203+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:09:48.203+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:09:48.215+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:09:48.212+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:09:48.216+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:09:48.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.044 seconds
[2024-11-10T06:10:18.810+0000] {processor.py:157} INFO - Started process (PID=59673) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:10:18.811+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:10:18.812+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:10:18.811+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:10:18.823+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:10:18.821+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:10:18.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:10:18.849+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.041 seconds
[2024-11-10T06:10:48.993+0000] {processor.py:157} INFO - Started process (PID=59740) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:10:48.994+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:10:48.995+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:10:48.995+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:10:49.007+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:10:49.004+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:10:49.008+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:10:49.026+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.035 seconds
[2024-11-10T06:11:19.226+0000] {processor.py:157} INFO - Started process (PID=59807) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:11:19.227+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:11:19.228+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:11:19.228+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:11:19.240+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:11:19.237+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:11:19.241+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:11:19.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.041 seconds
[2024-11-10T06:11:49.431+0000] {processor.py:157} INFO - Started process (PID=59874) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:11:49.432+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:11:49.433+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:11:49.432+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:11:49.445+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:11:49.442+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:11:49.446+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:11:49.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.035 seconds
[2024-11-10T06:12:19.611+0000] {processor.py:157} INFO - Started process (PID=59941) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:12:19.612+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:12:19.613+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:12:19.613+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:12:19.625+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:12:19.622+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:12:19.625+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:12:19.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.041 seconds
[2024-11-10T06:12:49.872+0000] {processor.py:157} INFO - Started process (PID=60008) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:12:49.873+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:12:49.873+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:12:49.873+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:12:49.885+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:12:49.882+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:12:49.886+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:12:49.904+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:13:20.163+0000] {processor.py:157} INFO - Started process (PID=60075) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:13:20.164+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:13:20.165+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:13:20.165+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:13:20.179+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:13:20.176+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:13:20.180+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:13:20.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.037 seconds
[2024-11-10T06:13:50.348+0000] {processor.py:157} INFO - Started process (PID=60142) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:13:50.349+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:13:50.349+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:13:50.349+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:13:50.362+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:13:50.359+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:13:50.363+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:13:50.379+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:14:20.565+0000] {processor.py:157} INFO - Started process (PID=60209) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:14:20.566+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:14:20.567+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:14:20.566+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:14:20.578+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:14:20.575+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:14:20.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:14:20.603+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.040 seconds
[2024-11-10T06:14:50.723+0000] {processor.py:157} INFO - Started process (PID=60276) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:14:50.724+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:14:50.725+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:14:50.725+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:14:50.738+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:14:50.735+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:14:50.739+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:14:50.756+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.035 seconds
[2024-11-10T06:15:21.016+0000] {processor.py:157} INFO - Started process (PID=60329) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:15:21.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:15:21.018+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:15:21.018+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:15:21.030+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:15:21.027+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:15:21.031+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:15:21.056+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.042 seconds
[2024-11-10T06:15:51.149+0000] {processor.py:157} INFO - Started process (PID=60393) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:15:51.150+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:15:51.150+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:15:51.150+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:15:51.164+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:15:51.161+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:15:51.165+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:15:51.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.037 seconds
[2024-11-10T06:16:21.319+0000] {processor.py:157} INFO - Started process (PID=60460) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:16:21.320+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:16:21.321+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:16:21.321+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:16:21.332+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:16:21.330+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:16:21.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:16:21.351+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:16:51.582+0000] {processor.py:157} INFO - Started process (PID=60527) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:16:51.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:16:51.584+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:16:51.584+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:16:51.596+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:16:51.593+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:16:51.596+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:16:51.612+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:17:21.795+0000] {processor.py:157} INFO - Started process (PID=60594) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:17:21.796+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:17:21.796+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:17:21.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:17:21.808+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:17:21.805+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:17:21.809+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:17:21.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:17:51.984+0000] {processor.py:157} INFO - Started process (PID=60661) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:17:51.985+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:17:51.986+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:17:51.985+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:17:51.997+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:17:51.995+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:17:51.998+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:17:52.023+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.042 seconds
[2024-11-10T06:18:22.186+0000] {processor.py:157} INFO - Started process (PID=60728) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:18:22.186+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:18:22.187+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:18:22.187+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:18:22.199+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:18:22.197+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:18:22.200+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:18:22.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:18:52.400+0000] {processor.py:157} INFO - Started process (PID=60795) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:18:52.401+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:18:52.402+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:18:52.401+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:18:52.413+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:18:52.411+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:18:52.414+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:18:52.430+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:19:22.550+0000] {processor.py:157} INFO - Started process (PID=60856) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:19:22.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:19:22.551+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:19:22.551+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:19:22.564+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:19:22.561+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:19:22.565+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:19:22.582+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:19:52.803+0000] {processor.py:157} INFO - Started process (PID=60923) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:19:52.804+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:19:52.805+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:19:52.805+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:19:52.817+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:19:52.814+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:19:52.818+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:19:52.834+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:20:23.185+0000] {processor.py:157} INFO - Started process (PID=60990) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:20:23.186+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:20:23.187+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:20:23.186+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:20:23.199+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:20:23.197+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:20:23.200+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:20:23.223+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.041 seconds
[2024-11-10T06:20:53.554+0000] {processor.py:157} INFO - Started process (PID=61057) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:20:53.554+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:20:53.555+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:20:53.555+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:20:53.569+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:20:53.566+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:20:53.570+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:20:53.587+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.036 seconds
[2024-11-10T06:21:23.889+0000] {processor.py:157} INFO - Started process (PID=61085) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:21:23.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:21:23.890+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:21:23.890+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:21:23.904+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:21:23.901+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:21:23.905+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:21:23.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.035 seconds
[2024-11-10T06:21:54.187+0000] {processor.py:157} INFO - Started process (PID=61152) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:21:54.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:21:54.188+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:21:54.188+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:21:54.200+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:21:54.197+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:21:54.201+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:21:54.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:22:24.492+0000] {processor.py:157} INFO - Started process (PID=61219) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:22:24.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:22:24.494+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:22:24.494+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:22:24.505+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:22:24.503+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:22:24.506+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:22:24.530+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.040 seconds
[2024-11-10T06:22:54.840+0000] {processor.py:157} INFO - Started process (PID=61286) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:22:54.841+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:22:54.841+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:22:54.841+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:22:54.853+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:22:54.850+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:22:54.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:22:54.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:23:25.190+0000] {processor.py:157} INFO - Started process (PID=61370) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:23:25.191+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:23:25.191+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:23:25.191+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:23:25.203+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:23:25.200+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:23:25.204+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:23:25.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:23:55.516+0000] {processor.py:157} INFO - Started process (PID=61437) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:23:55.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:23:55.518+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:23:55.518+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:23:55.530+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:23:55.527+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:23:55.531+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:23:55.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:24:25.748+0000] {processor.py:157} INFO - Started process (PID=61525) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:24:25.748+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:24:25.749+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:24:25.749+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:24:25.762+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:24:25.759+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:24:25.763+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:24:25.782+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.037 seconds
[2024-11-10T06:24:56.108+0000] {processor.py:157} INFO - Started process (PID=61588) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:24:56.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:24:56.110+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:24:56.109+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:24:56.121+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:24:56.119+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:24:56.122+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:24:56.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.035 seconds
[2024-11-10T06:25:26.230+0000] {processor.py:157} INFO - Started process (PID=61655) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:25:26.231+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:25:26.232+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:25:26.232+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:25:26.244+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:25:26.241+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:25:26.245+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:25:26.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.041 seconds
[2024-11-10T06:25:56.530+0000] {processor.py:157} INFO - Started process (PID=61739) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:25:56.530+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:25:56.531+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:25:56.531+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:25:56.542+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:25:56.540+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:25:56.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:25:56.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:26:26.598+0000] {processor.py:157} INFO - Started process (PID=61806) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:26:26.599+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:26:26.600+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:26:26.600+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:26:26.612+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:26:26.609+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:26:26.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:26:26.638+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.042 seconds
[2024-11-10T06:26:57.336+0000] {processor.py:157} INFO - Started process (PID=61890) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:26:57.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:26:57.338+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:26:57.338+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:26:57.350+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:26:57.347+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:26:57.351+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:26:57.370+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.037 seconds
[2024-11-10T06:27:27.604+0000] {processor.py:157} INFO - Started process (PID=61957) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:27:27.604+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:27:27.605+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:27:27.605+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:27:27.617+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:27:27.615+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:27:27.618+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:27:27.644+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.043 seconds
[2024-11-10T06:27:57.891+0000] {processor.py:157} INFO - Started process (PID=62041) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:27:57.892+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:27:57.893+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:27:57.892+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:27:57.904+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:27:57.901+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:27:57.905+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:27:57.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.035 seconds
[2024-11-10T06:28:28.121+0000] {processor.py:157} INFO - Started process (PID=62108) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:28:28.122+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:28:28.123+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:28:28.123+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:28:28.135+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:28:28.132+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:28:28.135+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:28:28.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.033 seconds
[2024-11-10T06:28:58.330+0000] {processor.py:157} INFO - Started process (PID=62175) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:28:58.330+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:28:58.331+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:28:58.331+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:28:58.343+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:28:58.340+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-10T06:28:58.343+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:28:58.362+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.034 seconds
[2024-11-10T06:29:18.111+0000] {processor.py:157} INFO - Started process (PID=62242) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:29:18.112+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:29:18.113+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:29:18.112+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:29:18.120+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:29:18.120+0000] {dagbag.py:324} INFO - File /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py assumed to contain no DAGs. Skipping.
[2024-11-10T06:29:18.121+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:29:18.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.029 seconds
[2024-11-10T06:29:48.441+0000] {processor.py:157} INFO - Started process (PID=62309) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:29:48.442+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:29:48.443+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:29:48.443+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:29:48.448+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:29:48.448+0000] {dagbag.py:324} INFO - File /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py assumed to contain no DAGs. Skipping.
[2024-11-10T06:29:48.449+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:29:48.461+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.022 seconds
[2024-11-10T06:30:01.561+0000] {processor.py:157} INFO - Started process (PID=62314) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:30:01.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py for tasks to queue
[2024-11-10T06:30:01.563+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:30:01.563+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:30:01.570+0000] {logging_mixin.py:151} INFO - [2024-11-10T06:30:01.570+0000] {dagbag.py:324} INFO - File /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py assumed to contain no DAGs. Skipping.
[2024-11-10T06:30:01.570+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py
[2024-11-10T06:30:01.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/rename_columns.py took 0.024 seconds
