[2024-11-17T08:12:20.994+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-17T08:12:13.556141+00:00/task_id=natural_gas_feature_engineering permission to 509
[2024-11-17T08:12:20.995+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-17T08:12:13.556141+00:00/task_id=natural_gas_feature_engineering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-17T08:12:13.556141+00:00/task_id=natural_gas_feature_engineering'
[2024-11-17T08:12:21.040+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-17T08:12:13.556141+00:00/task_id=natural_gas_feature_engineering permission to 509
[2024-11-17T08:12:21.041+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-17T08:12:13.556141+00:00/task_id=natural_gas_feature_engineering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-17T08:12:13.556141+00:00/task_id=natural_gas_feature_engineering'
[2024-11-17T08:12:21.080+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_pipeline.natural_gas_feature_engineering manual__2024-11-17T08:12:13.556141+00:00 [queued]>
[2024-11-17T08:12:21.093+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_pipeline.natural_gas_feature_engineering manual__2024-11-17T08:12:13.556141+00:00 [queued]>
[2024-11-17T08:12:21.094+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-17T08:12:21.119+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): natural_gas_feature_engineering> on 2024-11-17 08:12:13.556141+00:00
[2024-11-17T08:12:21.131+0000] {standard_task_runner.py:57} INFO - Started process 146710 to run task
[2024-11-17T08:12:21.137+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_training_pipeline', 'natural_gas_feature_engineering', 'manual__2024-11-17T08:12:13.556141+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/model_training_pipeline_dag/model_training_dag.py', '--cfg-path', '/tmp/tmpvi30r8uf']
[2024-11-17T08:12:21.143+0000] {standard_task_runner.py:85} INFO - Job 271: Subtask natural_gas_feature_engineering
[2024-11-17T08:12:21.236+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-17T08:12:13.556141+00:00/task_id=natural_gas_feature_engineering permission to 509
[2024-11-17T08:12:21.237+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-17T08:12:13.556141+00:00/task_id=natural_gas_feature_engineering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-17T08:12:13.556141+00:00/task_id=natural_gas_feature_engineering'
[2024-11-17T08:12:21.239+0000] {task_command.py:415} INFO - Running <TaskInstance: model_training_pipeline.natural_gas_feature_engineering manual__2024-11-17T08:12:13.556141+00:00 [running]> on host 16801ac1f6e4
[2024-11-17T08:12:21.372+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_pipeline' AIRFLOW_CTX_TASK_ID='natural_gas_feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T08:12:13.556141+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T08:12:13.556141+00:00'
[2024-11-17T08:13:37.992+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-11-17T08:13:37.998+0000] {process_utils.py:131} INFO - Sending 15 to group 146710. PIDs of all processes in the group: [146710]
[2024-11-17T08:13:37.999+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 146710
[2024-11-17T08:13:38.000+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-17T08:13:38.093+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=146710, status='terminated', exitcode=0, started='08:12:20') (146710) terminated with exit code 0
