[2024-11-18T10:29:02.966+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=merge_dataframes permission to 509
[2024-11-18T10:29:02.966+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=merge_dataframes permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=merge_dataframes'
[2024-11-18T10:29:02.999+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=merge_dataframes permission to 509
[2024-11-18T10:29:03.001+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=merge_dataframes permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=merge_dataframes'
[2024-11-18T10:29:03.032+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_pipeline.merge_dataframes manual__2024-11-18T10:28:51.600561+00:00 [queued]>
[2024-11-18T10:29:03.042+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_pipeline.merge_dataframes manual__2024-11-18T10:28:51.600561+00:00 [queued]>
[2024-11-18T10:29:03.042+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-18T10:29:03.056+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): merge_dataframes> on 2024-11-18 10:28:51.600561+00:00
[2024-11-18T10:29:03.071+0000] {standard_task_runner.py:57} INFO - Started process 24556 to run task
[2024-11-18T10:29:03.073+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_training_pipeline', 'merge_dataframes', 'manual__2024-11-18T10:28:51.600561+00:00', '--job-id', '314', '--raw', '--subdir', 'DAGS_FOLDER/model_training_pipeline_dag/model_training_dag.py', '--cfg-path', '/tmp/tmpodgbwe2b']
[2024-11-18T10:29:03.078+0000] {standard_task_runner.py:85} INFO - Job 314: Subtask merge_dataframes
[2024-11-18T10:29:03.127+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=merge_dataframes permission to 509
[2024-11-18T10:29:03.127+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=merge_dataframes permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=merge_dataframes'
[2024-11-18T10:29:03.128+0000] {task_command.py:415} INFO - Running <TaskInstance: model_training_pipeline.merge_dataframes manual__2024-11-18T10:28:51.600561+00:00 [running]> on host 16801ac1f6e4
[2024-11-18T10:29:03.203+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_pipeline' AIRFLOW_CTX_TASK_ID='merge_dataframes' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T10:28:51.600561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T10:28:51.600561+00:00'
[2024-11-18T10:31:52.982+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-11-18T10:31:52.995+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=model_training_pipeline, task_id=merge_dataframes, execution_date=20241118T102851, start_date=20241118T102903, end_date=20241118T103152
[2024-11-18T10:31:53.040+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-18T10:31:53.068+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
