[2024-11-08T23:49:56.857+0000] {processor.py:157} INFO - Started process (PID=211) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:49:56.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:49:56.861+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:49:56.860+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:49:56.908+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:49:56.901+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:49:56.911+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:49:56.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.118 seconds
[2024-11-08T23:50:28.635+0000] {processor.py:157} INFO - Started process (PID=275) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:50:28.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:50:28.638+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:28.637+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:50:28.660+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:28.654+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:50:28.662+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:50:28.690+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.059 seconds
[2024-11-08T23:51:00.737+0000] {processor.py:157} INFO - Started process (PID=339) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:51:00.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:51:00.740+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:00.739+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:51:00.758+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:00.754+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:51:00.759+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:51:00.784+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.052 seconds
[2024-11-08T23:51:31.828+0000] {processor.py:157} INFO - Started process (PID=403) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:51:31.829+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:51:31.830+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:31.830+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:51:31.850+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:31.846+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:51:31.852+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:51:31.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.052 seconds
[2024-11-08T23:52:02.714+0000] {processor.py:157} INFO - Started process (PID=467) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:52:02.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:52:02.716+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:02.715+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:52:02.735+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:02.731+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:52:02.737+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:52:02.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.055 seconds
[2024-11-08T23:52:34.188+0000] {processor.py:157} INFO - Started process (PID=531) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:52:34.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:52:34.190+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:34.189+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:52:34.207+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:34.203+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:52:34.208+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:52:34.231+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.046 seconds
[2024-11-08T23:53:06.183+0000] {processor.py:157} INFO - Started process (PID=597) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:53:06.184+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:53:06.186+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:06.185+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:53:06.206+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:06.201+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:53:06.207+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:53:06.233+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.054 seconds
[2024-11-08T23:53:37.404+0000] {processor.py:157} INFO - Started process (PID=661) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:53:37.405+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:53:37.406+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:37.406+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:53:37.429+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:37.422+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:53:37.430+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:53:37.460+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.060 seconds
[2024-11-08T23:54:08.833+0000] {processor.py:157} INFO - Started process (PID=723) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:54:08.834+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:54:08.836+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:08.835+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:54:08.861+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:08.856+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:54:08.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:54:08.893+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.065 seconds
[2024-11-08T23:54:39.963+0000] {processor.py:157} INFO - Started process (PID=787) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:54:39.964+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:54:39.964+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:39.964+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:54:39.985+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:39.980+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:54:39.989+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:54:40.014+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.054 seconds
[2024-11-08T23:55:10.703+0000] {processor.py:157} INFO - Started process (PID=851) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:55:10.704+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:55:10.705+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:10.705+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:55:10.723+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:10.719+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:55:10.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:55:10.752+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.052 seconds
[2024-11-08T23:55:41.906+0000] {processor.py:157} INFO - Started process (PID=915) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:55:41.907+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:55:41.909+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:41.908+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:55:41.938+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:41.935+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:55:41.940+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:55:41.961+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.058 seconds
[2024-11-08T23:56:13.030+0000] {processor.py:157} INFO - Started process (PID=981) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:56:13.031+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:56:13.031+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:13.031+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:56:13.049+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:13.045+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:56:13.051+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:56:13.072+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.045 seconds
[2024-11-08T23:56:44.049+0000] {processor.py:157} INFO - Started process (PID=1043) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:56:44.050+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:56:44.051+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:44.051+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:56:44.068+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:44.064+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:56:44.069+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:56:44.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.044 seconds
[2024-11-08T23:57:15.038+0000] {processor.py:157} INFO - Started process (PID=1107) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:57:15.039+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:57:15.040+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:15.040+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:57:15.059+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:15.055+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:57:15.061+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:57:15.086+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.052 seconds
[2024-11-08T23:57:46.505+0000] {processor.py:157} INFO - Started process (PID=1173) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:57:46.507+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:57:46.509+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:46.509+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:57:46.590+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:46.572+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:57:46.598+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:57:46.630+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.128 seconds
[2024-11-08T23:58:16.919+0000] {processor.py:157} INFO - Started process (PID=1235) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:58:16.920+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:58:16.921+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:16.921+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:58:16.940+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:16.936+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:58:16.942+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:58:16.962+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.046 seconds
[2024-11-08T23:58:47.886+0000] {processor.py:157} INFO - Started process (PID=1299) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:58:47.886+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:58:47.887+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:47.887+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:58:47.904+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:47.900+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:58:47.905+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:58:47.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.041 seconds
[2024-11-08T23:59:18.964+0000] {processor.py:157} INFO - Started process (PID=1363) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:59:18.965+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:59:18.966+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:18.965+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:59:18.986+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:18.981+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:59:18.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:59:19.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.052 seconds
[2024-11-08T23:59:49.886+0000] {processor.py:157} INFO - Started process (PID=1427) to work on /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:59:49.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/extraction/noaa_api.py for tasks to queue
[2024-11-08T23:59:49.888+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:49.888+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:59:49.905+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:49.902+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/extraction/noaa_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:59:49.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction/noaa_api.py
[2024-11-08T23:59:49.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/extraction/noaa_api.py took 0.043 seconds
