[2024-11-08T23:49:53.321+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:49:53.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:49:53.326+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:49:53.325+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:49:56.550+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:49:56.543+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:49:56.552+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:49:56.588+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 3.271 seconds
[2024-11-08T23:50:27.467+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:50:27.469+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:50:27.471+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:27.470+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:50:28.427+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:28.421+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:50:28.429+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:50:28.461+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.998 seconds
[2024-11-08T23:50:59.417+0000] {processor.py:157} INFO - Started process (PID=322) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:50:59.418+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:50:59.420+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:59.420+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:51:00.556+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:00.552+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:51:00.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:51:00.581+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 1.170 seconds
[2024-11-08T23:51:31.029+0000] {processor.py:157} INFO - Started process (PID=386) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:51:31.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:51:31.031+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:31.031+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:51:31.678+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:31.672+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:51:31.679+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:51:31.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.674 seconds
[2024-11-08T23:52:01.787+0000] {processor.py:157} INFO - Started process (PID=447) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:52:01.787+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:52:01.788+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:01.788+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:52:02.539+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:02.534+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:52:02.541+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:52:02.560+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.777 seconds
[2024-11-08T23:52:33.002+0000] {processor.py:157} INFO - Started process (PID=514) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:52:33.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:52:33.004+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:33.004+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:52:34.037+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:34.032+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:52:34.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:52:34.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 1.060 seconds
[2024-11-08T23:53:04.556+0000] {processor.py:157} INFO - Started process (PID=576) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:53:04.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:53:04.559+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:04.559+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:53:05.985+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:05.979+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:53:05.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:53:06.018+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 1.528 seconds
[2024-11-08T23:53:36.505+0000] {processor.py:157} INFO - Started process (PID=642) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:53:36.506+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:53:36.508+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:36.508+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:53:37.098+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:37.091+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:53:37.099+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:53:37.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.630 seconds
[2024-11-08T23:54:07.911+0000] {processor.py:157} INFO - Started process (PID=706) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:54:07.912+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:54:07.915+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:07.914+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:54:08.600+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:08.568+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:54:08.603+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:54:08.648+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.741 seconds
[2024-11-08T23:54:39.292+0000] {processor.py:157} INFO - Started process (PID=770) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:54:39.293+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:54:39.294+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:39.294+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:54:39.807+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:39.802+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:54:39.809+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:54:39.833+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.545 seconds
[2024-11-08T23:55:10.044+0000] {processor.py:157} INFO - Started process (PID=834) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:55:10.046+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:55:10.047+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:10.047+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:55:10.526+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:10.519+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:55:10.528+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:55:10.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.514 seconds
[2024-11-08T23:55:41.213+0000] {processor.py:157} INFO - Started process (PID=898) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:55:41.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:55:41.216+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:41.215+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:55:41.733+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:41.728+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:55:41.735+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:55:41.755+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.545 seconds
[2024-11-08T23:56:12.411+0000] {processor.py:157} INFO - Started process (PID=962) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:56:12.412+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:56:12.413+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:12.413+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:56:12.873+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:12.868+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:56:12.875+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:56:12.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.489 seconds
[2024-11-08T23:56:43.426+0000] {processor.py:157} INFO - Started process (PID=1026) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:56:43.427+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:56:43.428+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:43.428+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:56:43.897+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:43.891+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:56:43.899+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:56:43.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.500 seconds
[2024-11-08T23:57:14.364+0000] {processor.py:157} INFO - Started process (PID=1090) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:57:14.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:57:14.366+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:14.366+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:57:14.873+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:14.868+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:57:14.875+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:57:14.900+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.540 seconds
[2024-11-08T23:57:45.213+0000] {processor.py:157} INFO - Started process (PID=1154) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:57:45.215+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:57:45.218+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:45.217+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:57:45.881+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:45.859+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:57:45.888+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:57:45.917+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.708 seconds
[2024-11-08T23:58:16.140+0000] {processor.py:157} INFO - Started process (PID=1215) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:58:16.141+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:58:16.143+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:16.142+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:58:16.706+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:16.701+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:58:16.708+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:58:16.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.591 seconds
[2024-11-08T23:58:47.249+0000] {processor.py:157} INFO - Started process (PID=1282) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:58:47.250+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:58:47.251+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:47.251+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:58:47.750+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:47.745+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:58:47.751+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:58:47.773+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.526 seconds
[2024-11-08T23:59:18.265+0000] {processor.py:157} INFO - Started process (PID=1346) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:59:18.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:59:18.267+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:18.267+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:59:18.779+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:18.773+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:59:18.781+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:59:18.810+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.548 seconds
[2024-11-08T23:59:49.221+0000] {processor.py:157} INFO - Started process (PID=1410) to work on /opt/airflow/dags/utils/aws.py
[2024-11-08T23:59:49.222+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/utils/aws.py for tasks to queue
[2024-11-08T23:59:49.223+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:49.223+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:59:49.748+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:49.743+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/utils/aws.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/aws.py", line 9, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:59:49.750+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/aws.py
[2024-11-08T23:59:49.770+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/utils/aws.py took 0.553 seconds
