[2024-11-08T23:49:52.681+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:49:52.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:49:52.687+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:49:52.686+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:49:52.748+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:49:52.741+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:49:52.756+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:49:52.809+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.133 seconds
[2024-11-08T23:50:23.139+0000] {processor.py:157} INFO - Started process (PID=235) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:50:23.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:50:23.142+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:23.142+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:50:23.165+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:23.158+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:50:23.166+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:50:23.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.084 seconds
[2024-11-08T23:50:54.099+0000] {processor.py:157} INFO - Started process (PID=299) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:50:54.101+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:50:54.102+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:54.102+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:50:54.141+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:54.135+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:50:54.143+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:50:54.175+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.089 seconds
[2024-11-08T23:51:24.714+0000] {processor.py:157} INFO - Started process (PID=363) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:51:24.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:51:24.718+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:24.716+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:51:24.737+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:24.732+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:51:24.738+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:51:24.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.055 seconds
[2024-11-08T23:51:55.468+0000] {processor.py:157} INFO - Started process (PID=427) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:51:55.470+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:51:55.473+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:55.472+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:51:55.495+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:55.490+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:51:55.496+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:51:55.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.076 seconds
[2024-11-08T23:52:25.665+0000] {processor.py:157} INFO - Started process (PID=491) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:52:25.666+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:52:25.670+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:25.667+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:52:25.690+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:25.685+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:52:25.692+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:52:25.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.068 seconds
[2024-11-08T23:52:56.126+0000] {processor.py:157} INFO - Started process (PID=555) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:52:56.128+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:52:56.130+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:56.129+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:52:56.158+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:56.153+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:52:56.159+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:52:56.202+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.084 seconds
[2024-11-08T23:53:26.924+0000] {processor.py:157} INFO - Started process (PID=619) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:53:26.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:53:26.926+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:26.926+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:53:26.943+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:26.940+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:53:26.945+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:53:26.968+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.048 seconds
[2024-11-08T23:53:57.504+0000] {processor.py:157} INFO - Started process (PID=683) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:53:57.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:53:57.506+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:57.505+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:53:57.530+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:57.524+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:53:57.531+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:53:57.572+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.071 seconds
[2024-11-08T23:54:27.918+0000] {processor.py:157} INFO - Started process (PID=747) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:54:27.919+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:54:27.921+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:27.920+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:54:27.937+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:27.934+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:54:27.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:54:27.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.052 seconds
[2024-11-08T23:54:58.634+0000] {processor.py:157} INFO - Started process (PID=811) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:54:58.635+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:54:58.636+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:58.636+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:54:58.653+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:58.650+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:54:58.654+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:54:58.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.054 seconds
[2024-11-08T23:55:28.748+0000] {processor.py:157} INFO - Started process (PID=875) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:55:28.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:55:28.750+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:28.750+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:55:28.769+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:28.763+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:55:28.770+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:55:28.794+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.049 seconds
[2024-11-08T23:55:58.926+0000] {processor.py:157} INFO - Started process (PID=939) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:55:58.927+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:55:58.928+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:58.927+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:55:58.949+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:58.945+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:55:58.950+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:55:58.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.047 seconds
[2024-11-08T23:56:29.984+0000] {processor.py:157} INFO - Started process (PID=1003) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:56:29.985+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:56:29.986+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:29.986+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:56:30.006+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:30.001+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:56:30.008+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:56:30.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.056 seconds
[2024-11-08T23:57:00.925+0000] {processor.py:157} INFO - Started process (PID=1067) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:57:00.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:57:00.926+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:00.926+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:57:00.942+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:00.938+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:57:00.943+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:57:00.964+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.043 seconds
[2024-11-08T23:57:31.148+0000] {processor.py:157} INFO - Started process (PID=1131) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:57:31.148+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:57:31.150+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:31.149+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:57:31.167+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:31.164+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:57:31.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:57:31.194+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.049 seconds
[2024-11-08T23:58:01.587+0000] {processor.py:157} INFO - Started process (PID=1195) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:58:01.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:58:01.590+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:01.590+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:58:01.636+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:01.626+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:58:01.639+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:58:01.667+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.083 seconds
[2024-11-08T23:58:31.851+0000] {processor.py:157} INFO - Started process (PID=1259) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:58:31.853+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:58:31.854+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:31.853+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:58:31.876+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:31.871+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:58:31.877+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:58:31.900+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.052 seconds
[2024-11-08T23:59:02.846+0000] {processor.py:157} INFO - Started process (PID=1323) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:59:02.847+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:59:02.848+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:02.848+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:59:02.865+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:02.862+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:59:02.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:59:02.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.051 seconds
[2024-11-08T23:59:33.810+0000] {processor.py:157} INFO - Started process (PID=1387) to work on /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:59:33.811+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py for tasks to queue
[2024-11-08T23:59:33.812+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:33.812+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:59:33.831+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:33.827+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py", line 3, in <module>
    from full_program.airflow.dags.utils.config import *
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:59:33.832+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py
[2024-11-08T23:59:33.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/pivot_data.py took 0.058 seconds
