[2024-11-21T10:26:34.207+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-21T10:17:46.337766+00:00/task_id=train_model permission to 509
[2024-11-21T10:26:34.208+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-21T10:17:46.337766+00:00/task_id=train_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-21T10:17:46.337766+00:00/task_id=train_model'
[2024-11-21T10:26:34.237+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-21T10:17:46.337766+00:00/task_id=train_model permission to 509
[2024-11-21T10:26:34.238+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-21T10:17:46.337766+00:00/task_id=train_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-21T10:17:46.337766+00:00/task_id=train_model'
[2024-11-21T10:26:34.260+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_pipeline.train_model manual__2024-11-21T10:17:46.337766+00:00 [queued]>
[2024-11-21T10:26:34.268+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_pipeline.train_model manual__2024-11-21T10:17:46.337766+00:00 [queued]>
[2024-11-21T10:26:34.268+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-11-21T10:26:34.285+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_model> on 2024-11-21 10:17:46.337766+00:00
[2024-11-21T10:26:34.300+0000] {standard_task_runner.py:57} INFO - Started process 17247 to run task
[2024-11-21T10:26:34.302+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_training_pipeline', 'train_model', 'manual__2024-11-21T10:17:46.337766+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/model_training_pipeline_dag/model_training_dag.py', '--cfg-path', '/tmp/tmpqpk9i9v_']
[2024-11-21T10:26:34.305+0000] {standard_task_runner.py:85} INFO - Job 341: Subtask train_model
[2024-11-21T10:26:34.349+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-21T10:17:46.337766+00:00/task_id=train_model permission to 509
[2024-11-21T10:26:34.349+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-21T10:17:46.337766+00:00/task_id=train_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-21T10:17:46.337766+00:00/task_id=train_model'
[2024-11-21T10:26:34.351+0000] {task_command.py:415} INFO - Running <TaskInstance: model_training_pipeline.train_model manual__2024-11-21T10:17:46.337766+00:00 [running]> on host 16801ac1f6e4
[2024-11-21T10:26:34.431+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T10:17:46.337766+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T10:17:46.337766+00:00'
[2024-11-21T10:31:47.520+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-11-21T10:31:47.525+0000] {process_utils.py:131} INFO - Sending 15 to group 17247. PIDs of all processes in the group: [17247]
[2024-11-21T10:31:47.526+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 17247
[2024-11-21T10:31:47.590+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-21T10:31:47.899+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=17247, status='terminated', exitcode=0, started='10:26:33') (17247) terminated with exit code 0
